// Generated by spice/gen_ac30_refs.py (ngspice) - do not edit.
#pragma once

inline constexpr double kAc30RefB3 = 291.9, kAc30RefB4 = 267.4, kAc30RefB5 = 245.9;

struct Ac30PreampConfig { const char* name; bool normalInput; float normal, topBoost, treble, bass; };
struct Ac30PiConfig { const char* name; float toneCut, master; };
struct Ac30Case { int config; float amplitude, frequency; double fundamental, thdPercent; };

inline constexpr Ac30PreampConfig kAc30PreampConfigs[] = {
    { "tb_default", false, 0.0f, 5.0f, 6.0f, 5.0f },
    { "tb_bright_hot", false, 0.0f, 8.0f, 8.0f, 2.0f },
    { "normal", true, 7.0f, 5.0f, 5.0f, 5.0f },
};

inline constexpr Ac30Case kAc30PreampCases[] = {
    { 0, 0.01f, 100.0f, 0.0763841, 0.143431 },
    { 0, 0.01f, 500.0f, 0.132444, 0.258981 },
    { 0, 0.01f, 2000.0f, 0.223137, 0.689078 },
    { 0, 0.01f, 6000.0f, 0.563228, 0.914683 },
    { 0, 0.1f, 1000.0f, 1.40573, 8.28833 },
    { 0, 0.5f, 1000.0f, 5.13212, 33.9889 },
    { 1, 0.01f, 100.0f, 0.0828237, 0.536112 },
    { 1, 0.01f, 500.0f, 0.412366, 2.53568 },
    { 1, 0.01f, 2000.0f, 1.39292, 3.60544 },
    { 1, 0.01f, 6000.0f, 2.46764, 2.33938 },
    { 1, 0.1f, 1000.0f, 5.84688, 42.1657 },
    { 1, 0.5f, 1000.0f, 6.75786, 81.9819 },
    { 2, 0.01f, 100.0f, 0.130782, 0.0905529 },
    { 2, 0.01f, 500.0f, 0.135303, 0.0914966 },
    { 2, 0.01f, 2000.0f, 0.144175, 0.10172 },
    { 2, 0.01f, 6000.0f, 0.178313, 0.100454 },
    { 2, 0.1f, 1000.0f, 1.37389, 0.946249 },
    { 2, 0.5f, 1000.0f, 6.79408, 4.85169 },
};

inline constexpr Ac30PiConfig kAc30PiConfigs[] = {
    { "cut0_master10", 0.0f, 10.0f },
    { "cut5_master6", 5.0f, 6.0f },
    { "cut10_master3", 10.0f, 3.0f },
};

inline constexpr Ac30Case kAc30PiCases[] = {
    { 0, 0.1f, 100.0f, 3.37015, 0.0263034 },
    { 0, 0.1f, 1000.0f, 3.02278, 0.0327833 },
    { 0, 0.1f, 5000.0f, 3.00249, 0.0326656 },
    { 1, 0.1f, 100.0f, 2.20009, 0.0323244 },
    { 1, 0.1f, 1000.0f, 1.764, 0.043398 },
    { 1, 0.1f, 5000.0f, 1.7291, 0.0443135 },
    { 2, 0.1f, 100.0f, 0.446941, 0.0509449 },
    { 2, 0.1f, 1000.0f, 0.396254, 0.0370137 },
    { 2, 0.1f, 5000.0f, 0.142441, 0.0304707 },
};
