// Generated by spice/gen_sss002_refs.py (ngspice) - do not edit.
#pragma once

struct Sss002Config { const char* name; float treble, middle, bass, volume, master; int high, low; bool bright, deep, accent; };
struct Sss002Case { int config; float amplitude, frequency; double fundamental, thdPercent; };

inline constexpr Sss002Config kSss002Configs[] = {
    { "default", 5.0f, 5.0f, 5.0f, 5.0f, 5.0f, 4, 4, true, false, false },
    { "bright_high1_low1_deep", 7.0f, 3.0f, 6.0f, 7.0f, 6.0f, 1, 1, true, true, true },
    { "dark_high7_low7", 3.0f, 8.0f, 3.0f, 4.0f, 4.0f, 7, 7, false, false, false },
};

inline constexpr Sss002Case kSss002Cases[] = {
    { 0, 0.01f, 100.0f, 0.005182, 0.0488294 },
    { 0, 0.01f, 500.0f, 0.00784005, 0.112935 },
    { 0, 0.01f, 2000.0f, 0.0698818, 0.0559266 },
    { 0, 0.01f, 6000.0f, 0.169168, 0.06407 },
    { 0, 0.1f, 1000.0f, 0.227343, 1.11936 },
    { 0, 0.5f, 1000.0f, 1.1286, 5.6591 },
    { 1, 0.01f, 100.0f, 0.240303, 0.0458191 },
    { 1, 0.01f, 500.0f, 0.101915, 0.236618 },
    { 1, 0.01f, 2000.0f, 1.80235, 0.0915045 },
    { 1, 0.01f, 6000.0f, 3.55084, 0.238906 },
    { 1, 0.1f, 1000.0f, 5.3801, 1.07146 },
    { 1, 0.5f, 1000.0f, 23.8106, 7.5681 },
    { 2, 0.01f, 100.0f, 0.000472086, 0.0873613 },
    { 2, 0.01f, 500.0f, 0.00418896, 0.061243 },
    { 2, 0.01f, 2000.0f, 0.00638795, 0.033752 },
    { 2, 0.01f, 6000.0f, 0.00292749, 0.0263498 },
    { 2, 0.1f, 1000.0f, 0.0683251, 0.386902 },
    { 2, 0.5f, 1000.0f, 0.340235, 1.94829 },
};
