#!/usr/bin/env python3
"""
Generates ngspice reference data for the SSS #002 dry preamp (V1 -> tone stack -> V4 -> High/Low
filters -> U37/U38 -> mixer -> master -> first PI grid) and writes tests/Sss002SpiceReference.h.

The netlist is the reconstruction's circuit (SSS No 002.asc) with the real Koren triode models
(inter-electrode capacitances, grid diode), not the plugin's simplifications - so the test checks
the plugin's modelling choices, not just its solver. Requires ngspice on PATH.
"""
import math, os, re, subprocess, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'tests', 'Sss002SpiceReference.h')
CLOSED, OPEN = 1.0, 1e10
HIGH_CAPS = [0, 150e-12, 330e-12, 1e-9, 2.4e-9, 5.1e-9, 10e-9]

def pot_lin(k): return min(max(k / 10.0, 1e-5), 0.99999)
def pot_audio(k): return min(max(pot_lin(k) ** (math.log(0.1) / math.log(0.5)), 1e-5), 0.99999)

def netlist(c, amp, freq):
    t, b, v, r = pot_audio(c['treble']), pot_audio(c['bass']), pot_audio(c['volume']), pot_audio(c['master'])
    m = pot_lin(c['middle'])
    rhs = CLOSED if c['high'] == 1 else OPEN
    ch = HIGH_CAPS[1] if c['high'] == 1 else HIGH_CAPS[c['high'] - 1]
    lows = ['n39', 't1', 't2', 't3', 't4', 't5', 'n40']
    low_lines = '\n'.join(f"Rlow{i} lc {n} {CLOSED if i == c['low'] - 1 else OPEN}" for i, n in enumerate(lows))
    period = 1.0 / freq
    return f"""* SSS #002 dry preamp reference
.include {os.path.join(HERE, 'koren_sss002.inc')}
Vhta hta 0 343.94
Vht4 ht4 0 348.79
Vin in 0 SIN(0 {amp} {freq})
R22 in g1 34k
XV1 p1 g1 k1 5751
R2 hta p1 100k
R1 k1 kb1 1.5k
C2 k1 kb1 5u
R62 kb1 0 100
C15 p4 nf1 0.1u
R54 nf1 kb1 100k
C1 p1 tt 360p
R3 p1 sl 100k
C3 sl bt 0.1u
C34 sl md 0.047u
Rmid md 0 {100e3 * m}
RtA tt out {250e3 * (1 - t)}
RtB out tb {250e3 * t}
C35 tb 0 4.7n
RbA bt bw {250e3 * (1 - b)}
RbB bw bb {250e3 * b}
R7 bb 0 1.8k
R63 bw out 100k
RvA out rev {1e6 * (1 - v)}
RvB rev 0 {1e6 * v}
C4 out br 250p
Rbr br rev {CLOSED if c['bright'] else OPEN}
Rd1 bt da {270e3 if c['deep'] else OPEN}
Rd2 rev da {270e3 if c['deep'] else OPEN}
C36 da db 0.01u
R66 da db 1meg
R67 db 0 10k
R69 rev g4 68k
XV4 p4 g4 k4 5751
R5 hta p4 100k
R4 k4 kb4 1.5k
C5 k4 kb4 5u
R68 kb4 0 100
C47 k38 nf2 0.22u
R82 nf2 kb4 470k
C6 p4 c6 0.01u
C37 c6 n30 0.001u
R53 c6 n55 100k
L2 n55 lch 0.3
RL2 lch n39 59
R34 n39 n30 470k
R70 n30 g37 820k
C44 n30 0 3n
Rhs n30 g37 {rhs}
Chc n30 hc {ch}
Rhc hc g37 {CLOSED}
R71 g37 0 100k
R72 n39 t1 39k
R73 t1 t2 68k
R74 t2 t3 100k
R75 t3 t4 180k
R76 t4 t5 270k
R77 t5 n40 390k
R78 n40 0 12k
C45 n39 n40 0.01u
{low_lines}
R79 lc g37 270k
XU37 p37 g37 k37 7025
R80 ht4 p37 100k
R81 k37 0 1k
C46 k37 0 1u
XU38 ht4 p37 k38 7025
R83 k38 0 100k
R84 k38 n45 220k
R85 n45 k40 220k
Vk40 k40 0 DC 207
C49 n45 mt 0.01u
RmA mt mw {1e6 * (1 - r)}
RmB mw 0 {1e6 * r}
C50 mt ac 1n
Rac ac mw {CLOSED if c['accent'] else OPEN}
C9 mw pg 0.02u
R10 pg 0 1meg
.options reltol=1e-4 abstol=1e-12 vntol=1e-7
.control
tran {period / 400} {0.3 + 20 * period} 0.3 {period / 400}
fourier {freq} v(pg)
.endc
.end
"""

def run(c, amp, freq):
    with tempfile.NamedTemporaryFile('w', suffix='.cir', delete=False) as f:
        f.write(netlist(c, amp, freq))
        name = f.name
    out = subprocess.run(['ngspice', '-b', name], capture_output=True, text=True).stdout
    os.unlink(name)
    thd = float(re.search(r'THD:\s*([0-9.eE+-]+)', out).group(1))
    h1 = None
    for line in out.splitlines():
        p = line.split()
        if len(p) >= 3 and p[0] == '1' and abs(float(p[1]) - freq) < 1e-3 * freq:
            h1 = float(p[2])
    return h1, thd

CONFIGS = [
    dict(name='default', treble=5, middle=5, bass=5, volume=5, master=5, high=4, low=4, bright=True, deep=False, accent=False),
    dict(name='bright_high1_low1_deep', treble=7, middle=3, bass=6, volume=7, master=6, high=1, low=1, bright=True, deep=True, accent=True),
    dict(name='dark_high7_low7', treble=3, middle=8, bass=3, volume=4, master=4, high=7, low=7, bright=False, deep=False, accent=False),
]
CASES = [(0.01, 100.0), (0.01, 500.0), (0.01, 2000.0), (0.01, 6000.0), (0.1, 1000.0), (0.5, 1000.0)]

rows = []
for ci, c in enumerate(CONFIGS):
    for amp, freq in CASES:
        h1, thd = run(c, amp, freq)
        rows.append((ci, amp, freq, h1, thd))
        print(c['name'], amp, freq, h1, thd)

with open(OUT, 'w') as f:
    f.write('// Generated by spice/gen_sss002_refs.py (ngspice) - do not edit.\n#pragma once\n\n')
    f.write('struct Sss002Config { const char* name; float treble, middle, bass, volume, master; int high, low; bool bright, deep, accent; };\n')
    f.write('struct Sss002Case { int config; float amplitude, frequency; double fundamental, thdPercent; };\n\n')
    f.write('inline constexpr Sss002Config kSss002Configs[] = {\n')
    for c in CONFIGS:
        f.write(f"    {{ \"{c['name']}\", {float(c['treble'])}f, {float(c['middle'])}f, {float(c['bass'])}f, {float(c['volume'])}f, {float(c['master'])}f, {c['high']}, {c['low']}, "
                f"{str(c['bright']).lower()}, {str(c['deep']).lower()}, {str(c['accent']).lower()} }},\n")
    f.write('};\n\ninline constexpr Sss002Case kSss002Cases[] = {\n')
    for ci, amp, freq, h1, thd in rows:
        f.write(f'    {{ {ci}, {amp}f, {freq}f, {h1!r}, {thd!r} }},\n')
    f.write('};\n')
